services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile   # now points to root Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend